### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hiroppy** [abouthiroppy/nicohaco#7]
- [x] modify UI
  - [x] css for small size
- [x] Add Video
- [x] run on windows
- [ ] refactor https://github.com/nicohaco/nicohaco/issues/14
- [ ] local mylist
- [ ] add user mylist
- [x] upgrade some packages(because of react-slider)
- [x] autoupdate using https://github.com/zeit/hazel
- [ ] loader and around componentWillMount
- [x] Update README
